### ISSUE TITLE
更新版本后，执行报错：

### ISSUE THREAD

**Issue by qq122356** [michael-liumh/binlog2sql#1]
sudo python3 binlog2sql.py -h127.0.0.1 -P3306 -uroot -p -dhzb -tt_sys_user --only-dml --start-file='binlog.000010'
更新版本后，执行报错（更新前正常）
更新后的命令在操作远端的polardb可以正常

Traceback (most recent call last):
  File "binlog2sql.py", line 158, in <module>
    binlog2sql = Binlog2sql(connection_settings=conn_setting, start_file=args.start_file, start_pos=args.start_pos,
  File "binlog2sql.py", line 46, in __init__
    self.connection = pymysql.connect(**self.conn_setting)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 706, in __init__
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 931, in connect
    self._get_server_information()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1269, in _get_server_information
    self.server_charset = charset_by_id(lang).name
  File "/usr/local/lib/python3.8/dist-packages/pymysql/charset.py", line 38, in by_id
    return self._by_id[id]
KeyError: 255

**Comment by michael-liumh** [comment]
更新啥版本？pymysql?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 中午1:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [michael-liumh/binlog2sql] 更新版本后，执行报错： (Issue #1)




 
Traceback (most recent call last):
 File "binlog2sql.py", line 158, in 
 binlog2sql = Binlog2sql(connection_settings=conn_setting, start_file=args.start_file, start_pos=args.start_pos,
 File "binlog2sql.py", line 46, in init
 self.connection = pymysql.connect(**self.conn_setting)
 File "/usr/local/lib/python3.8/dist-packages/pymysql/init.py", line 90, in Connect
 return Connection(*args, **kwargs)
 File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 706, in init
 self.connect()
 File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 931, in connect
 self._get_server_information()
 File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1269, in _get_server_information
 self.server_charset = charset_by_id(lang).name
 File "/usr/local/lib/python3.8/dist-packages/pymysql/charset.py", line 38, in by_id
 return self._by_id[id]
 KeyError: 255
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qq122356** [comment]
> 更新啥版本？pymysql?
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年11月9日(周二) 中午1:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [michael-liumh/binlog2sql] 更新版本后，执行报错： (Issue #1) Traceback (most recent call last): File "binlog2sql.py", line 158, in binlog2sql = Binlog2sql(connection_settings=conn_setting, start_file=args.start_file, start_pos=args.start_pos, File "binlog2sql.py", line 46, in init self.connection = pymysql.connect(**self.conn_setting) File "/usr/local/lib/python3.8/dist-packages/pymysql/init.py", line 90, in Connect return Connection(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 706, in init self.connect() File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 931, in connect self._get_server_information() File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1269, in _get_server_information self.server_charset = charset_by_id(lang).name File "/usr/local/lib/python3.8/dist-packages/pymysql/charset.py", line 38, in by_id return self._by_id[id] KeyError: 255 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qq122356** [comment]
> > 更新啥版本？pymysql?

之前用的是 <https://github.com/danfengcao/binlog2sql/  > 这边的binlog2sql

**Comment by qq122356** [comment]
> 更新啥版本？pymysql?

之前用的是 <https://github.com/danfengcao/binlog2sql/ > 这边的binlog2sql
