### ISSUE TITLE
没有匹配到position报错

### ISSUE THREAD

**Issue by sbwfnhn** [michael-liumh/binlog2sql#5]
有个小bug，在没有匹配到position的日志时，会报错，日志报错有点误导排查方向。
```
[root@localhost binlog2sql-master]# python3 binlog2sql.py  -h127.0.0.1 -P3306 -uroot -p -d databases -t user --flashback --start-file='mysql-bin.000124' --start-position=4 --stop-position=137742613 > ~/rollback.sql
Password: 
[2022-08-04 13:56:26,572] [sort_binlog2sql_result_utils:get_file_line_count] [153] [INFO] Getting line count of file tmp/127.0.0.1.3306 ...
[2022-08-04 13:56:26,595] [binlog2sql_util:handle_rollback_sql] [749] [INFO] handling...
Traceback (most recent call last):
  File "/home/tools/binlog2sql-master/binlog2sql_util.py", line 750, in handle_rollback_sql
    for line in yield_file(tmp_file, chunk_size=1):
  File "/home/tools/binlog2sql-master/utils/sort_binlog2sql_result_utils.py", line 104, in yield_file
    with open(filename, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/127.0.0.1.3306_tmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "binlog2sql.py", line 300, in <module>
    main(command_line_args)
  File "binlog2sql.py", line 294, in main
    binlog2sql.process_binlog()
  File "binlog2sql.py", line 263, in process_binlog
    self.result_dir, tmp_file, self.chunk_size, self.tmp_dir, self.result_file)
  File "/home/tools/binlog2sql-master/binlog2sql_util.py", line 772, in handle_rollback_sql
    os.remove(tmp_file)
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/127.0.0.1.3306_tmp'
```

**Comment by wjainiya** [comment]
请问这个错误是怎么改呢 @sbwfnhn

**Comment by michael-liumh** [comment]
已修复
